apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: arenaondemandtojoark
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  image: {{ image }}
  env:
    - name: ARENAONDEMANDTOJOARK_ENDPOINTS_DOKARKIV_URL
      value: {{ ARENAONDEMANDTOJOARK_ENDPOINTS_DOKARKIV_URL }}
    - name: ARENAONDEMANDTOJOARK_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ ARENAONDEMANDTOJOARK_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: ARENAONDEMANDTOJOARK_ENDPOINTS_ONDEMAND
      value: {{ ARENAONDEMANDTOJOARK_ENDPOINTS_ONDEMAND }}
    - name: FILNAVN
      value: {{ filnavn }}
    - name: OPERASJON
      value: {{ operasjon }}
    - name: SPRING_DATASOURCE_URL
      value: {{ SPRING_DATASOURCE_URL }}
  azure:
    application:
      enabled: true
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: {{ ARENAONDEMANDTOJOARK_DB }}
        mountPath: /var/run/secrets/nais.io/arenaondemandtojoarkDB